name: CI/CD

on:
  push:
    branches:
    - main
  release:
    types:
    - published

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 15.x

    - name: Install Dependencies
      run: yarn install --frozen-lockfile

    - name: Test
      run: yarn test
      if: runner.os != 'Linux'

    - name: Test with xvfb
      run: xvfb-run -a yarn test
      if: runner.os == 'Linux'

    - name: Publish
      if: success() && startsWith( github.ref, 'refs/tags/v') && matrix.os == 'ubuntu-latest'
      run: yarn deploy
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
      
